// vue-frontend/src/components/API-Tests.vue
<template>
  <div class="test-block">
    <div v-if="showSQLTESTS">
      <div class="inner-container">
        <textarea v-model="sqlRequest" placeholder="Enter sql operation"></textarea>
      </div>
      <div class="inner-container">
        <h3>SQL statement: </h3>
        {{ sqlRequest }}
      </div>
      <button @click="getDataFromDatabase">Get</button>
      <div class="inner-container">
        <h3>Column Names</h3>
        <div v-for="sqlColumnName in sqlColumnNames" :key="sqlColumnName" class="inner-container">
          {{ sqlColumnName }}
        </div>
      </div>
      <div class="inner-container">
        <textarea v-model="stringMovieToConvert" placeholder="String movie"></textarea>
      </div>
      <div class="inner-container">
        <select v-model="selectedOperationType">
          <option v-for="operation in sqlOperations" :value="operation" :key="operation">
            {{ operation }}
          </option>
        </select>
      </div>
      <button @click="getDataFromDatabase">Operate on movie</button>
    </div>

    <div v-if="showALGORITHMSTESTS">
      <div>
        <label for="pattern-to-match">Pattern to match</label>
        <input v-model="patternToMatch" id="pattern-to-match">
        <label for="selected-algorithm-type">Search algorithm</label>
        <input v-model="selectedAlgorithmType" id="selected-algorithm-type">
        <button @click="checkAlgorithm">Check</button>
      </div>
      <h3>Algorithms</h3>
      <div v-for="algorithmType in algorithmTypes" :key="algorithmType" class="inner-container">
        {{ algorithmType }}
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "API-Tests",
  props: {
    isRails: Boolean,
    showSQLTESTS: Boolean,
    showALGORITHMSTESTS: Boolean,
    sqlColumnNames: Array,
    algorithmTypes: Array,
    sqlOperations: Array,
    getResult: Function
  },
  data() {
    return {
      springAPIURL: "http://localhost:8080/spring-api/",
      railsAPRIURL: "http://localhost:3000/rails-api/",
      selectedOperationType: "UPDATE",
      sqlRequest: "",
      patternToMatch: "",
      selectedAlgorithmType: "",
      result: undefined,
      stringMovieToConvert: ""
    }
  },
  methods: {
    checkAlgorithm() {
      if (this.isRails) {
        axios.get(this.railsAPRIURL + "get/algorithm", {
          params: {
            patternToSearch: this.patternToMatch,
            algorithmType: this.selectedAlgorithmType
          }
        }).then(result => this.getResult(result))
      } else {
        axios.get(this.springAPIURL + "get/algorithm", {
          params: {
            patternToSearch: this.patternToMatch,
            algorithmType: this.selectedAlgorithmType
          }
        }).then(result => this.getResult(result))
      }
    },
    getDataFromDatabase() {
      if (this.isRails) {
        if (this.sqlRequest.toLowerCase().includes("select")) {
          axios.get(this.railsAPRIURL + "get", {
            params: {
              query: this.sqlRequest
            }
          }).then(result => this.getResult(result))
        } else {
          axios.post(this.railsAPRIURL + "operate", {}, {
            params: {
              operationType: this.selectedOperationType,
              stringMovies: this.stringMovieToConvert
            }
          }).then(result => this.getResult(result))
        }
      } else {
        if (this.sqlRequest.toLowerCase().includes("select")) {
          axios.get(this.springAPIURL + "get", {
            params: {
              query: this.sqlRequest
            }
          }).then(result => this.getResult(result))
        } else {
          axios.post(this.springAPIURL + "operate", {}, {
            params: {
              operationType: this.selectedOperationType,
              stringMovies: this.stringMovieToConvert
            }
          }).then(result => this.getResult(result))
        }
      }
    }
  }
}
</script>

<style scoped>

</style>

// svelte-frontend/src/components/APITests.svelte
<main>
    <div class="test-block">
        {#if showSQLTESTS}
            <div>
                <div class="inner-container">
                    <textarea bind:value="{sqlRequest}" placeholder="Enter sql operation"></textarea>
                </div>
                <div class="inner-container">
                    <h3>SQL statement: </h3>
                    { sqlRequest }
                </div>
                <button on:click={getDataFromDatabase}>Get</button>
                <div class="inner-container">
                    <h3>Column Names</h3>
                    {#each sqlColumnNames as sqlColumnName}
                        <div class="inner-container">
                            { sqlColumnName }
                        </div>
                    {/each}
                </div>
            </div>

            <div class="inner-container">
                <textarea bind:value={stringMovieToConvert} placeholder="String movie"></textarea>
            </div>
            <div class="inner-container">
                <select bind:value={selectedOperationType}>
                    {#each sqlOperations as operation}
                        <option>
                            { operation }
                        </option>
                    {/each}
                </select>
            </div>
            <button on:click={getDataFromDatabase}>Operate on movie</button>
        {/if}

        {#if showALGORITHMSTESTS}
            <div>
                <div>
                    <label for="pattern-to-match">Pattern to match</label>
                    <input bind:value="{patternToMatch}" id="pattern-to-match">
                    <label for="selected-algorithm-type">Search algorithm</label>
                    <input bind:value="{selectedAlgorithmType}" id="selected-algorithm-type">
                    <button on:click="{checkAlgorithm}">Check</button>
                </div>
                <h3>Algorithms</h3>
                {#each algorithmTypes as algorithmType}
                    <div class="inner-container">
                        {algorithmType}
                    </div>
                {/each}
            </div>
        {/if}
    </div>
</main>

<script>
    import axios from 'axios'

    export let springAPIURL = "http://localhost:8080/spring-api/"
    export let railsAPRIURL = "http://localhost:3000/rails-api/"
    export let sqlRequest = ""
    export let patternToMatch = ""
    export let selectedAlgorithmType = ""
    export let resultData = undefined
    export let stringMovieToConvert = ""
    export let selectedOperationType = "UPDATE"
    export let isRails
    export let showSQLTESTS
    export let showALGORITHMSTESTS
    export let sqlColumnNames
    export let algorithmTypes
    export let sqlOperations

    function checkAlgorithm() {
        if (isRails) {
            axios.get(railsAPRIURL + "get/algorithm", {
                params: {
                    patternToSearch: patternToMatch,
                    algorithmType: selectedAlgorithmType
                }
            }).then(result => resultData = result)
        } else {
            axios.get(springAPIURL + "get/algorithm", {
                params: {
                    patternToSearch: patternToMatch,
                    algorithmType: selectedAlgorithmType
                }
            }).then(result => resultData = result)
        }
    }

    function getDataFromDatabase() {
        if (isRails) {
            if (sqlRequest.toLowerCase().includes("select")) {
                axios.get(railsAPRIURL + "get", {
                    params: {
                        query: sqlRequest
                    }
                }).then(result => resultData = result)
            } else {
                axios.post(railsAPRIURL + "operate", {}, {
                    params: {
                        operationType: selectedOperationType,
                        stringMovies: stringMovieToConvert
                    }
                }).then(result => resultData = result)
            }
        } else {
            if (sqlRequest.toLowerCase().includes("select")) {
                axios.get(springAPIURL + "get", {
                    params: {
                        query: sqlRequest
                    }
                }).then(result => resultData = result)
            } else {
                axios.post(springAPIURL + "operate", {}, {
                    params: {
                        operationType: selectedOperationType,
                        stringMovies: stringMovieToConvert
                    }
                }).then(result => resultData = result)
            }
        }
    }
</script>
