// svelte-frontend/src/components/ResultsTests.svelte
<main>
    {#if result != undefined}
        <div>
            {#if result.testStartDate != undefined}
                <div v-if="result.testStartDate != undefined">
                    <h4>Start of test: </h4>
                    <p>{result.testStartDate}</p>
                </div>
            {/if}
            {#if result.testStopDate != undefined}
                <div>
                    <h4>End of Test: </h4>
                    <p>{result.testStopDate}</p>
                </div>
            {/if}
            {#if result.durationInMilli != undefined}
                <div>
                    <h4>Duration: </h4>
                    <p>{result.durationInMilli}</p>
                </div>
            {/if}
            {#if result.operationResult != undefined}
                <div>
                    <h4>Affected rows: </h4>
                    <p>{result.operationResult}</p>
                </div>
            {/if}
            {#if result.stringMovies != undefined}
                <div>
                    <h4>Result from SQL: </h4>
                    <p>{ result.stringMovies }</p>
                </div>
            {/if}
            {#if result.movies != undefined}
                <div>
                    <h4>Result from SQL: </h4>
                    <p>{result.movies}</p>
                </div>
            {/if}
            {#if result.resultList != undefined}
                <div>
                    <h4>Result from text search: </h4>
                    <p>{result.resultList}</p>
                </div>
            {/if}
        </div>
    {/if}
</main>

<script>
   export let result = {
       testStartDate: "",
       testStopDate: "",
       durationInMilli: "",
       operationResult: "",
       stringMovies: [],
       movies: [],
       resultList: []
   }
</script>

// vue-frontend/src/components/Results-Tests.vue
<template>
  <div v-if="result != undefined">
    <div v-if="result.testStartDate != undefined">
      <h4>Start of test: </h4>
      <p>{{ result.testStartDate }}</p>
    </div>
    <div v-if="result.testStopDate != undefined">
      <h4>End of Test: </h4>
      <p>{{ result.testStopDate }}</p>
    </div>
    <div v-if="result.durationInMilli != undefined">
      <h4>Duration: </h4>
      <p>{{ result.durationInMilli }}</p>
    </div>
    <div v-if="result.operationResult != undefined">
      <h4>Affected rows: </h4>
      <p>{{ result.operationResult }}</p>
    </div>
    <div v-if="result.stringMovies != undefined">
      <h4>String movies: </h4>
      <p>{{ result.stringMovies }}</p>
    </div>
    <div v-if="result.movies != undefined">
      <h4>Movies: </h4>
      <p>{{ result.movies }}</p>
    </div>
    <div v-if="result.resultList != undefined">
      <h4>Result from text search: </h4>
      <p>{{ result.resultList }}</p>
    </div>
  </div>
</template>

<script>
export default {
  name: "Results-Tests",
  props: {
    result_: Object
  },
  data() {
    return {
      result: {
        testStartDate: "",
        testStopDate: "",
        durationInMilli : "",
        operationResult : "",
        stringMovies: [],
        movies: [],
        resultList: []
      },
    }
  }
}
</script>

<style scoped>

</style>
